use_frameworks!

platform :ios, '9.0'

target 'YHLongPressDragSort_Example' do
  pod 'YHLongPressDragSort', :path => '../'

  target 'YHLongPressDragSort_Tests' do
    inherit! :search_paths

    
  end
  
  pod 'Masonry'
  pod 'MLeaksFinder', :git => 'https://github.com/Tencent/MLeaksFinder', :configurations => ['Debug']
  
end
